name: Wails build

on: [push]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'Pantheon'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'Pantheon'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'Pantheon'
            platform:  'darwin/universal'
            os: 'macos-latest'
          - name: 'Pantheon'
            platform:  'darwin/arm64'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
          - uses: dAppServer/wails-build-action@main
          - uses: oven-sh/setup-bun@v2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.24'
