name: Build Pantheon

on: [push]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    permissions: write-all
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'Pantheon'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
            artifact_name: 'Pantheon'
            asset_name: 'pantheon-linux-amd64'
          - name: 'Pantheon'
            platform:  'windows/amd64'
            os: 'windows-latest'
            artifact_name: 'Pantheon'
            asset_name: 'pantheon-windows-amd64'
#          - name: 'Pantheon'
#            platform:  'darwin/universal'
#            os: 'macos-latest'
          - name: 'Pantheon'
            platform:  'darwin/arm64'
            os: 'macos-latest'
            artifact_name: 'Pantheon.app.zip'
            asset_name: 'pantheon-macos-amd64'

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: oven-sh/setup-bun@v2
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        id: build
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.24'
