// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCredential(arg1) {
  return window['go']['main']['App']['AddCredential'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
