// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {tree} from '../models';

export function AddCredential(arg1:services.LdapConn):Promise<void>;

export function Connect(arg1:services.LdapConn):Promise<string>;

export function DeleteCredential(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetCredentials():Promise<Array<services.LdapConn>>;

export function GetEntries():Promise<tree.Tree>;

export function Search(arg1:string):Promise<tree.Tree>;

export function SearchOneLayer(arg1:string):Promise<tree.Tree>;

export function TestConnection(arg1:services.LdapConn):Promise<string>;
