// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tree} from '../models';

export function GetEntries():Promise<tree.Tree[map[string]interface {}]>;

export function Greet(arg1:string):Promise<string>;
